### ISSUE TITLE
ERROR: version number does not start with digit

### ISSUE THREAD

**Issue by tamsec** [ofalk/libdnet#38]
This error comes up when trying to install with checkinstall...I had to manually change the number and just guess what it was (I put 1.12?) since I didn't know.

**Comment by danilobondezan** [comment]
just rename the folder frim libdnet to libdnet-1.12 and will works

**Comment by ofalk** [comment]
This is quite old and I expect this is no longer valid. I'll close this issue, but should it be still valid, please feel free to reopen!
