### ISSUE TITLE
Undefined reference to 'intf_get'

### ISSUE THREAD

**Issue by ReturnToTheYouth** [ofalk/libdnet#44]
hello！
 I installed libdnet. when I call the intf_get function ,it shows the result:Undefined reference to 'intf_get'.

**Comment by mayank18049** [comment]
Can you give the log for the error?

**Comment by ofalk** [comment]
@ReturnToTheYouth Hey, is this still valid? I guess @mayank18049 would be happy to assist on this one.

**Comment by mayank18049** [comment]
@ofalk I have used the function in the testing so undefined reference should be resolved in my opinoin

**Comment by ofalk** [comment]
Thanks for the information @mayank18049 !
Given this update, I'll go ahead and close this issue!
