### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by ofalk** [ofalk/libdnet#45]
Hi!

We have a few packages in Fedora using libdnet. Now, that we're moving to Python 3, I had to remove the python subpackage, since it no longer builds against Python 3. This brings up the question: Is this project still alive???

**Comment by utoni** [comment]
Pretty much dead, unfortunately. Worst thing is that `libdnet` is a hard dependency to build and run snort. :/
There are already two PR for fixing the missing `sctp.h` header installation, but no reaction from the author.
Is it time for libdnet-ng?

**Comment by ofalk** [comment]
Thx for your comment @lnslbrty !
Since nothing is happening here any more, I'd also say it's time for libdnet-ng.
Anyone open for this? I'm not doing too much programming these days, so it might be better if someone else takes it.

**Comment by ofalk** [comment]
@lnslbrty Would you be interested in collaborating when cloning this?

**Comment by utoni** [comment]
I'm in.

**Comment by ofalk** [comment]
Awesome @lnslbrty !
I'll keep you posted. There are some things I need to check, but some way or the other, this is going to happen!

**Comment by ofalk** [comment]
It's here now:
https://github.com/ofalk/libdnet

Feel free to send over PRs!

Oliver

**Comment by utoni** [comment]
Incoming PR when I'm @home. :)

**Comment by ofalk** [comment]
Looking forward to it, @lnslbrty !

**Comment by ofalk** [comment]
Closing this issue, since I do co-ownership now.
