### ISSUE TITLE
CAN NOT INSTALL IN PYTHON3.6

### ISSUE THREAD

**Issue by alanfanh** [ofalk/libdnet#46]
Hello,I want use this package in python3.
So I use command  "pip3 install dnet" to installed ,but failed.
Is this project still alive?

**Comment by mayank18049** [comment]
The project was not available on python3 pip rn. You can use it on python2 via pip install.
If you want this library for python3, you may need to build the devel branch of this repository and then do a manual install

**Comment by ofalk** [comment]
As @mayank18049 stated, the current master branch is still on py2 - devel is already working with py3, but we haven't merged it over to the main branch yet and therefore not released anything in an official manner.
Does this answer you question @alanfanh ?

**Comment by ofalk** [comment]
@alanfanh Did you have a chance to look into the devel branch? From my point of view, I'd say this issue can be closed, given it's fixed in devel, but I'd love to have some confirmation from you!

**Comment by alanfanh** [comment]
@ofalk  OK，Thanks a lot。

**Comment by ofalk** [comment]
OK. Taking this as a confirmation and closing this issue.
