### ISSUE TITLE
check_addr.c

### ISSUE THREAD

**Issue by fun2yang** [ofalk/libdnet#48]
When I use this program, it will have the following problem，how to deal with it?????

Running suite(s): addr
92%: Checks: 13, Failures: 1, Errors: 0
check_addr.c:194:F:core:test_addr_pton:0: accepted triple octet

**Comment by ofalk** [comment]
@fun2yang As you might have noticed, I recently took over this project as maintainer.
Can you please let me know the exact steps how you ended up with this error + environment (esp. distribution/version)?

**Comment by ofalk** [comment]
No update since my last question. Closing, but @fun2yang feel free to reopen if this is still valid!
