### ISSUE TITLE
IPv6 patch

### ISSUE THREAD

**Issue by stsi** [ofalk/libdnet#54]
I've prepared an IPv6 patch for libdnet, mostly for fragroute-ipv6 project.
Do you want to merge it?
See https://github.com/stsi/fragroute-ipv6/issues/2#issuecomment-668445543 or the attached patch:
[libdnet-ng-ipv6.patch.txt](https://github.com/ofalk/libdnet/files/5068426/libdnet-ng-ipv6.patch.txt)

**Comment by ofalk** [comment]
Hi @stsi !
Thanks for opening this issue!
Sure, I'd be willing to include this fix. Can you open some pull request against devel? Once we have this integrated on the devel branch, we can think about cherry-picking this into master as well.

**Comment by ofalk** [comment]
Closing this as per https://github.com/ofalk/libdnet/pull/56
