### ISSUE TITLE
Change tests for addr_pton()

### ISSUE THREAD

**Issue by dwmcrobb** [ofalk/libdnet#62]
The ones where "localhost" is passed as the first argument should fail now, not pass.  There are two of them.  Sorry I missed these in my pull request.

https://github.com/ofalk/libdnet/blob/100f5b5c253dbf60facd0627c358de843c70d7cd/test/check/check_addr.c#L195

**Comment by ofalk** [comment]
Related to https://github.com/ofalk/libdnet/pull/61

**Comment by ofalk** [comment]
Should be ok now. Thanks for spotting it @dwmcrobb !
