### ISSUE TITLE
Allow building on Debian GNU/kFreeBSD

### ISSUE THREAD

**Issue by florianernst** [ofalk/libdnet#65]
Hello all,

there is a [Debian port to a FreeBSD kernel](https://www.debian.org/ports/kfreebsd-gnu/), and the patch below allows building dnet on it:
```
Index: libdnet/configure.ac
===================================================================
--- libdnet.orig/configure.ac
+++ libdnet/configure.ac
@@ -257,7 +257,7 @@ elif test "$ac_cv_header_net_pfvar_h" =
 elif test "$ac_cv_header_netinet_ip_fw_h" = yes ; then
      dnl XXX - ipfw2 support later...
      case "$host_os" in
-     *freebsd5*)
+     *freebsd5* | *kfreebsd*)
        AC_LIBOBJ([fw-none]) ;;
      *)
        AC_LIBOBJ([fw-ipfw]) ;;
```
Cheers,
Flo

**Comment by florianernst** [comment]
Forgot to mention: this patch was initially created by hesso@pool.math.tu-berlin.de for [Debian](https://sources.debian.org/src/libdumbnet/1.12-3/debian/patches/04kfreebsd.dpatch/).

**Comment by ofalk** [comment]
Fixed. Trail to original author here in this issue.
