### ISSUE TITLE
Error while configuring it. Please advise

### ISSUE THREAD

**Issue by ENB213-xiaoh** [ofalk/libdnet#78]
Error as shown here: configure: error: cannot find required auxiliary files: compile

**Comment by ofalk** [comment]
Indeed the config dir is missing.
Please run

```automake --add-missing```

before.

**Comment by ofalk** [comment]
Should be fixed in 1.16.3 - would be great if you could confirm this and we can close this issue.

**Comment by ENB213-xiaoh** [comment]
Confirmed. Thanks.

**Comment by ofalk** [comment]
Thanks for the confirmation and closing the issue. Glad this was solved so quickly. Thanks for reporting the issue!
