### ISSUE TITLE
Python bindings fail to build on macOS

### ISSUE THREAD

**Issue by jmroot** [ofalk/libdnet#82]
```
./dnet.c:781:10: fatal error: 'bsd/string.h' file not found
#include "bsd/string.h"
         ^~~~~~~~~~~~~~
1 error generated.
```
`strlcpy` and `strlcat` are declared in `string.h`. I'm not sure that `bsd/string.h` exists on BSD systems either, it might just be a Linux thing. You probably want to include `string.h` and then also include `bsd/string.h` if it exists.

**Comment by ofalk** [comment]
@jmroot Can you try the feature branch bsd-include to see if this fixes your issue on macOS? I'm afraid, but my Mac needs a reinstall before I can use it again.

**Comment by jmroot** [comment]
The branch still fails the same way I'm afraid.
```
./dnet.c:782:10: fatal error: 'bsd/string.h' file not found
#include "bsd/string.h"
         ^~~~~~~~~~~~~~
1 error generated.
```

There's no getting around the need to check whether the header exists before including it. Clang offers the `__has_include` macro, but it was only added to GCC very recently. The most portable way would still be to use `AC_CHECK_HEADER` in configure and substitute the result into either `setup.py` or `dnet.pyx`, and then include the header conditionally based on that. Something along the lines of:
```
#ifdef HAVE_BSD_STRING_H
#include <bsd/string.h>
#endif
```

**Comment by ofalk** [comment]
@jmroot would you be willing to provide a PR for this?

**Comment by jmroot** [comment]
Thanks for merging.

**Comment by ofalk** [comment]
You're the one who had most of the work, so thanks a lot to you @jmroot !
