### ISSUE TITLE
configure missing auxiliary file: compile?

### ISSUE THREAD

**Issue by pchapin** [ofalk/libdnet#83]
I'm trying to build libdnet from Git. I am getting the following:

    $ ./configure
    configure: error: cannot find required auxiliary files: compile

In fact, the auxiliary file `compile` is *not* in the `config` directory. My understanding is this file is only needed to support compilers that lack the `-o` and `-c` options. However, I'm using `gcc` which certainly does have those options. Is this something wrong with the `configure` script or something odd about my environment? I'm using Kali Linux. I'm unclear how I can best work around this.

**Comment by ofalk** [comment]
Hey @pchapin I guess you're using the master branch. You're better off - if you compile from source - to use the devel branch. As soon as I find time, I'll merge the current devel into master and then master should be fine as well again.

**Comment by pchapin** [comment]
Thanks, @ofalk, that was the problem. I was able to compile successfully from the devel branch.

**Comment by ofalk** [comment]
Thanks @pchapin for the confirmation. The current master branch and the new release should also work fine now.
